{
 "title": "Data engineer project final",
 "description": "Windows Prometheus monitors the display of the dashboard, adds the resource summary display, and optimizes the detailed display. Update to support windows_exporter 0.13.0.",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(windows_cs_hostname, job)"
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
   },
   {
    "name": "show_hostname",
    "label": "Show the hostname used",
    "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource overview (associated JOB item) currently selected host: 【$show_hostname】 instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$job：Server resource overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\"}"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\"} - 0"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"$job\"}/windows_logical_disk_size_bytes{job=~\"$job\"})"
    },
    {
     "expr": "windows_os_processes{job=~\"$job\"}"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})"
    }
   ]
  },
  {
   "title": "Hardware metrics / Resource details 【$show_hostname：$instance】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "repeat": "host",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100"
    }
   ]
  },
  {
   "title": "Usage rate of each partition",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk read and write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_os_processes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Number of processes"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}"
    }
   ]
  },
  { "title": "Software metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "In progress call",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "twitter_inprogress" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(twitter_latency_seconds_sum[5m])"
    }
   ]
  },
  {
   "title": "App called",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "twitter_calls_total" }
   ]
  },
  {
   "title": "Last time called",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "twitter_last_time_seconds" }
   ]
  }
 ]
}