version: "3"

services:
  app:
    build: .
    ports:
    - "5000:5000"
    - "8010:8010"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "${CADVISOR_PORT:-8082}:8080"
    restart: always